database:
  ip: '127.0.0.1' # MySQL的IP地址
  port: '3306' # MySQL的端口
  user: 'username' # MySQL的用户名
  password: 'password' # MySQL对应用户的密码
  database: 'dbname' # 使用的MySQL数据库名称

jwt:
  # token 密钥，生产环境时及的修改
  secret: 'demo@'
  # token 过期时间 单位：秒
  timeout: 3600

server:
  backend_url: 'http://127.0.0.1:8081/api/v1'