database:
  ip: '127.0.0.1' # MySQL的IP地址
  port: '3306' # MySQL的端口
  user: 'username' # MySQL的用户名
  password: 'password' # MySQL对应用户的密码
  database: 'dbname' # 使用的MySQL数据库名称

server:
  secret: 'demo@' # JWT secret