basePath: /api/v1
definitions:
  response.CommonA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.GetUserA:
    properties:
      code:
        type: integer
      message:
        type: string
      name:
        type: string
      success:
        type: boolean
    type: object
  response.LoginA:
    properties:
      id:
        type: integer
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  response.LoginQ:
    properties:
      name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
    required:
    - name
    - password
    type: object
  response.RegisterQ:
    properties:
      name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
    required:
    - name
    - password
    type: object
  response.UploadFileA:
    properties:
      code:
        type: integer
      message:
        type: string
      path:
        type: string
      success:
        type: boolean
    type: object
info:
  contact:
    email: bflaemswift@163.com
    name: BFlameSwift
    url: https://github.com/BFlameSwift
  description: Demo API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Demo API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 根据用户邮箱和密码等生成token，并将token返回给用户
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，Token
          schema:
            $ref: '#/definitions/response.LoginA'
      summary: 用户登录
      tags:
      - 登录模块
  /register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，Token
          schema:
            $ref: '#/definitions/response.CommonA'
      summary: 注册
      tags:
      - 登录模块
  /resource/upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传一个文件测试
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      - description: name
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/response.UploadFileA'
      summary: 上传文件
      tags:
      - 其他模块
  /users/{id}:
    get:
      consumes:
      - application/json
      description: 获取一个用户公开的详细资料
      parameters:
      - description: token
        in: header
        name: x-token
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，用户名
          schema:
            $ref: '#/definitions/response.GetUserA'
      summary: 获取用户资料
      tags:
      - 用户模块
swagger: "2.0"
