definitions:
  model.LoginQ:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Demo API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Demo API
  version: "1.0"
paths:
  /api/v1/account:
    post:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success": true, "message": "登录成功", "data": "model.User的所有信息"}'
          schema:
            type: string
      summary: Show an account
      tags:
      - accounts
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 根据用户邮箱和密码等生成token，并将token返回给用户
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success": true, "message": "登录成功", "data": "model.User的所有信息"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 登录模块
swagger: "2.0"
