info:
  contact: {}
  description: Demo API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Demo API
  version: "1.0"
paths:
  /user/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "登录成功", "data": "model.User的所有信息"}'
          schema:
            type: string
      tags:
      - user
swagger: "2.0"
