definitions:
  response.CommonA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.LoginQ:
    properties:
      password:
        minLength: 6
        type: string
      username:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  response.UploadFileQ:
    properties:
      name:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
  description: Demo API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Demo API
  version: "1.0"
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 根据用户邮箱和密码等生成token，并将token返回给用户
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success": true, "message": "登录成功", "data": "model.User的所有信息"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 登录模块
  /api/v1/resource/upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传一个文件测试
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      - description: name 文件
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.UploadFileQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/response.CommonA'
      summary: 上传文件
      tags:
      - 其他模块
swagger: "2.0"
