name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        run: sudo apt install sshpass

      - name: pull and build
        run: |
          sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}}
          cd /root/Project/Gin-demo;  
          python ./scripts/kill.py; 
          git config --global http.postBuffer 1048576000;
          git pull; 
          go build .;
          ./Gin-demo &;